import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
    faArchive,
    faBolt,
    faBomb,
    faBoxOpen,
    faBoxes,
    faCalendarCheck,
    faChessKing,
    faClock,
    faCode,
    faCogs,
    faDatabase,
    faDownload,
    faEnvelope,
    faFileArchive,
    faFileCode,
    faFire,
    faFolder,
    faGamepad,
    faHatWizard,
    faKey,
    faKeyboard,
    faLifeRing,
    faList,
    faLock,
    faMagic,
    faMedal,
    faMicrochip,
    faNetworkWired,
    faPen,
    faPlay,
    faRedo,
    faRobot,
    faRocket,
    faSave,
    faServer,
    faShieldAlt,
    faSlidersH,
    faStopCircle,
    faSync,
    faTag,
    faTasks,
    faTerminal,
    faTrash,
    faTrophy,
    faUndo,
    faUserPlus,
    faUsers,
} from '@fortawesome/free-solid-svg-icons';
import { TrophyTier } from '@/api/touchdown';

/**
 * Maps the icon keys stored against each trophy in the backend registry to the
 * Font Awesome icon rendered in the panel.
 */
const iconMap: Record<string, IconDefinition> = {
    archive: faArchive,
    bolt: faBolt,
    bomb: faBomb,
    'box-open': faBoxOpen,
    boxes: faBoxes,
    'calendar-check': faCalendarCheck,
    'chess-king': faChessKing,
    clock: faClock,
    code: faCode,
    cogs: faCogs,
    database: faDatabase,
    download: faDownload,
    envelope: faEnvelope,
    'file-archive': faFileArchive,
    'file-code': faFileCode,
    fire: faFire,
    folder: faFolder,
    gamepad: faGamepad,
    'hat-wizard': faHatWizard,
    key: faKey,
    keyboard: faKeyboard,
    'life-ring': faLifeRing,
    list: faList,
    lock: faLock,
    magic: faMagic,
    medal: faMedal,
    microchip: faMicrochip,
    'network-wired': faNetworkWired,
    pen: faPen,
    play: faPlay,
    redo: faRedo,
    robot: faRobot,
    rocket: faRocket,
    save: faSave,
    server: faServer,
    'shield-alt': faShieldAlt,
    'sliders-h': faSlidersH,
    'stop-circle': faStopCircle,
    sync: faSync,
    tag: faTag,
    tasks: faTasks,
    terminal: faTerminal,
    trash: faTrash,
    trophy: faTrophy,
    undo: faUndo,
    'user-plus': faUserPlus,
    users: faUsers,
};

export const trophyIcon = (key: string): IconDefinition => iconMap[key] || faTrophy;

export const tierColors: Record<TrophyTier, string> = {
    bronze: '#cd7f32',
    silver: '#c0c0c0',
    gold: '#ffd700',
    platinum: '#7de3f4',
};

export const tierNames: Record<TrophyTier, string> = {
    bronze: 'Bronze',
    silver: 'Silver',
    gold: 'Gold',
    platinum: 'Platinum',
};
